spring:
  application:
    name: gateway-service
  config:
    import:
      - "optional:configserver:http://configuration-service:8000/"
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres_db
    username: postgres
    password: root